version: '2.1'
services:
  socket_reader:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    command: sh -c "python3 /app/app/socker_reader/main.py"
  elastic:
    build:
      context: ./resources/elasticsearch
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    ports:
      - "9201:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    restart: always
    networks:
      - pw-bd-net
    ports:
      - "5602:5601"
    volumes:
    - ./resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  pw-bd-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.15.238.0/24
          gateway: 171.15.238.1
