version: '2.1'
services:
  index_rawdata:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    volumes:
      - .:/app/
    command: sh -c "./wait-for-it.sh -t 60 elastic:9200 && python3 ./app/gcp_pubsub/subscribers/main.py --project-id ${PROJECT_ID} --topic ${TOPIC_NAME}"
  acquire_rawdata:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    depends_on:
      - index_rawdata
    volumes:
      - .:/app/
    command: sh -c "python3 ./app/socket_reader/read.py --url ${WS_URL} --project-id ${PROJECT_ID} --topic ${TOPIC_NAME}"
  elastic:
    build:
      context: ./resources/elasticsearch
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    ports:
      - "9202:9200"
    environment:
      - cluster.name=pw-bd-project
      - node.name=master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    restart: always
    networks:
      - pw-bd-net
    ports:
      - "5602:5601"
    volumes:
      - ./resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  spark_streaming:
    image: pw-bd-project-scala_spark:latest
    restart: always
    networks:
      - pw-bd-net
    depends_on:
      - acquire_rawdata
    ports:
      - '8889:8888'
      - '4042:4040'
    command: "sh run.sh"

networks:
  pw-bd-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.15.238.0/24
          gateway: 171.15.238.1

volumes:
  esdata:
    driver: local