version: '2.1'
services:
  index_rawdata:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    volumes:
      - .:/app/
    command: sh -c "./wait-for-it.sh -t 60 elastic:9200 && python3 ./app/gcp_pubsub/subscribe.py --project-id ${PROJECT_ID} --topic ${TOPIC_NAME}"
  acquire_rawdata:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
    - pw-bd-net
    volumes:
    - .:/app/
    command: sh -c "python3 ./app/socket_reader/read.py --url ${WS_URL} --project-id ${PROJECT_ID} --topic ${TOPIC_NAME}"
  elastic:
    build:
      context: ./resources/elasticsearch
      dockerfile: Dockerfile
    restart: always
    networks:
      - pw-bd-net
    ports:
      - "9201:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    restart: always
    networks:
      - pw-bd-net
    ports:
      - "5602:5601"
    volumes:
      - ./resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  pw-bd-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.15.238.0/24
          gateway: 171.15.238.1
